export const ENDPOINTS = {
  HEALTH: '/api/health',
  WHISPER: '/api/whisper',
  AI: '/api/ai',
  GROQ: '/api/groq',
  GEMINI: '/api/gemini',
  ANALYZE_IMAGE: '/api/analyze-image',
  IMAGE_GEN: '/api/image-gen',
  TTS: '/api/tts',
  SUMMARIZE: '/api/summarize',
  STATS: '/api/stats',
  MEMORY_GLITCH: '/api/memory-glitch/generate',
  UPLOAD: '/api/upload',
  FACE_ANALYZE: '/api/face-analyze',
  DETECT_OBJECTS: '/api/detect-objects',
  FACE_HEALTH: '/api/face-health',
};
